<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="1" failures="0" hostname="ilab-dev" name="pytest" skipped="0" tests="1" time="140.153" timestamp="2022-09-03T18:02:07.647028"><testcase classname="" name="testsite" time="0.000"><error message="collection failure">Fixture "check_exists_by_xpath" called directly. Fixtures are not meant to be called directly,
but are created automatically when test functions request them as parameters.
See https://docs.pytest.org/en/stable/explanation/fixtures.html for more information about fixtures, and
https://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code.</error></testcase></testsuite></testsuites>